### ISSUE TITLE
没有visualize模块，方便分享一下吗？

### ISSUE THREAD

**Issue by bennyji** [ZeroE04/R-CenterNet#1]
报错为：
`Traceback (most recent call last):
  File "train.py", line 13, in <module>
    from visualize import Visualizer
ModuleNotFoundError: No module named 'visualize'`

**Comment by zhujingsong** [comment]
同问，没有visualize模块，方便分享一下吗？

**Comment by ZeroE04** [comment]
您好，visualize模块是不需要的，已经删除。

**Comment by ZeroE04** [comment]
> 报错为：
> `Traceback (most recent call last): File "train.py", line 13, in <module> from visualize import Visualizer ModuleNotFoundError: No module named 'visualize'`

删除所有visualize相关的代码即可
