### ISSUE TITLE
训练时RunTimeError：out of memory

### ISSUE THREAD

**Issue by xiyufeng2** [ZeroE04/R-CenterNet#10]
显存爆了，怀疑是batch_size太大，找不到改的地方。每次都是训练到第一个epoch第6个iter就断了

**Comment by ZeroE04** [comment]
1080Ti都无压力的，建议检查一下代码。
我上传了标签生成的代码，你也可以看看：
https://github.com/ZeroE04/R-CenterNet/tree/master/labelGenerator

**Comment by ZeroE04** [comment]
torch版本请升级到1.12
