### ISSUE TITLE
角度是怎么定义的

### ISSUE THREAD

**Issue by wuzuowuyou** [ZeroE04/R-CenterNet#16]
角度是怎么定义的？
R-CenterNet-master/imgs/001.jpg
比如这张图，里面只有一个大飞机，对应的xml。
<angle>0.54</angle>
这里的0.54是啥，是什么和什么之间的夹角，最好用图画出来说明一下。这样才直观。

```
<annotation>
	<folder>img</folder>
	<filename>001.jpg</filename>
	<path>F:\CV\毕业设计\打标签\img\001.jpg</path>
	<source>
		<database>Unknown</database>
	</source>
	<size>
		<width>958</width>
		<height>808</height>
		<depth>3</depth>
	</size>
	<segmented>0</segmented>
	<object>
		<name>aircraft</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>0</difficult>
		<robndbox>
			<cx>602.1491</cx>
			<cy>523.8509</cy>
			<w>93.0</w>
			<h>105.0</h>
			<angle>0.54</angle>
		</robndbox>
		<extra/>
	</object>
</annotation>
```

**Comment by wuzuowuyou** [comment]
<annotation>
	<folder>img</folder>
	<filename>001.jpg</filename>
	<path>F:\CV\毕业设计\打标签\img\001.jpg</path>
	<source>
		<database>Unknown</database>
	</source>
	<size>
		<width>958</width>
		<height>808</height>
		<depth>3</depth>
	</size>
	<segmented>0</segmented>
	<object>
		<name>aircraft</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>0</difficult>
		<robndbox>
			<cx>602.1491</cx>
			<cy>523.8509</cy>
			<w>93.0</w>
			<h>105.0</h>
			<angle>0.54</angle>
		</robndbox>
		<extra/>
	</object>
</annotation>

**Comment by wuzuowuyou** [comment]
```
<annotation>
	<folder>img</folder>
	<filename>001.jpg</filename>
	<path>F:\CV\毕业设计\打标签\img\001.jpg</path>
	<source>
		<database>Unknown</database>
	</source>
	<size>
		<width>958</width>
		<height>808</height>
		<depth>3</depth>
	</size>
	<segmented>0</segmented>
	<object>
		<name>aircraft</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>0</difficult>
		<robndbox>
			<cx>602.1491</cx>
			<cy>523.8509</cy>
			<w>93.0</w>
			<h>105.0</h>
			<angle>0.54</angle>
		</robndbox>
		<extra/>
	</object>
</annotation>
```

**Comment by ZeroE04** [comment]
https://github.com/ZeroE04/R-CenterNet/blob/master/labelGenerator/README.md

**Comment by wuzuowuyou** [comment]
旋转180°，相当于没转？
旋转180°，应该是转倒了啊！旋转360°，才相当于没转啊

**Comment by ZeroE04** [comment]
> 旋转180°，相当于没转？
> 旋转180°，应该是转倒了啊！旋转360°，才相当于没转啊

旋转210°的物体和旋转30°的物体使用的旋转框重合，可以认为是同一个。
