### ISSUE TITLE
关于角度的疑问

### ISSUE THREAD

**Issue by wuzuowuyou** [ZeroE04/R-CenterNet#19]
![图片](https://user-images.githubusercontent.com/24190729/101492774-1ed8b000-39a0-11eb-921c-1c66f340b45b.png)

centernet出来的是外接矩形，就是图片中蓝色框，然后角度是目标的倾斜角度（设为角度A）吗，然后是把蓝色的外接矩形的四个点根据目标中心旋转角度A吗？我看代码里面是这样

**Comment by wuzuowuyou** [comment]
整完之后的效果图是这样吗？
![图片](https://user-images.githubusercontent.com/24190729/101493273-d53c9500-39a0-11eb-8e58-03caaa67c433.png)
这里有个问题就是像这种情况由于是外接矩形，长条形状的目标会导致外接矩形旋转之后不贴合目标。。。
我不确定是不是这样的逻辑，希望有人能解惑。

**Comment by ZeroE04** [comment]
你下一个labelGenerator里面的工具，自己找个图像打一下就知道了。
