### ISSUE TITLE
代码中自定义的get_affine_transform函数用的是不是有问题？

### ISSUE THREAD

**Issue by JiliuLiSU** [ZeroE04/R-CenterNet#20]
trans_input = get_affine_transform(c, s, 0, [input_w, input_h])
训练测试都是这么用的，仿射变换后的的图片向右上角偏，左下角全黑？

**Comment by ZeroE04** [comment]
这部分遵循原CenterNet；仿射变换其实都是个人习惯问题，设计成自己网络可用的形式即可；不管是左上右下还是随机，不管是有意为之还是无意之举，只要结果的对得上，大多可以增加网络的健壮性，相当于数据扩充。

**Comment by JiliuLiSU** [comment]
谢谢回复，predict.py测试脚本中def pre_process(image):函数里的这句c = np.array([width / 2., height / 2.], dtype=np.float32)，width、height好像位置错了，位置互换后和训练时变换的图片是一致的，结果也能对上了

**Comment by ZeroE04** [comment]
感谢，已修正。
