### ISSUE TITLE
您好，请问有C++推断的示例代码吗？

### ISSUE THREAD

**Issue by huangzhenjie** [ZeroE04/R-CenterNet#21]

**Comment by ZeroE04** [comment]
过段时间会出，这段时间太忙了，不好意思

**Comment by ZeroE04** [comment]
> _No description provided._

过段时间出，最近太忙了，不好意思

**Comment by huangzhenjie** [comment]
你好，我想请教下你的部署方式，caffe？onnx+tensorRT?libtorch?还是其它呢？

**Comment by ZeroE04** [comment]
onnx+tensorRT；有时间的话会再写一个onnxruntime。

**Comment by huangzhenjie** [comment]
好的，谢谢
