### ISSUE TITLE
非常感谢！！！感觉这是我见过说的最详细的一个啦！:"D

### ISSUE THREAD

**Issue by enternityFan** [ZeroE04/R-CenterNet#23]
非常感谢！！！感觉这是我见过说的最详细的一个啦！:"D

**Comment by enternityFan** [comment]
请问我使用你的数据集和权重，可以训练，但是不能预测和评估，为什么？一评估就说不能除以0，一预测，预测结果不画图，我debug看到也是没有返回有效的点；

**Comment by huangzhenjie** [comment]
不能除以零是用的pytorch太新吧，对应修改下api就好

**Comment by enternityFan** [comment]
哇太感谢了；我刚想来说，我又下载了遍网络就莫名其妙的预测结果画图有结果了，应该是我改好了；大赞博主:"D

**Comment by enternityFan** [comment]
请问博主测试的训练集的mAP是多少？我在跑我自己的数据时，虽然只有144张图片，但每张图片的目标有7个以上，最后mAP只达到:
the F1 is :0.3599530240751615
the miou is:37889.90003630353
the mang is 0.14886717506014796
the p is 0.9273827534039334
the r is 0.22331511839708562
很多漏检测的，感觉不可思议；迭代了700次；没有预训练
我想问的是有机会提高mAP吗？我的目标很明显的

**Comment by ZeroE04** [comment]
100张单目标/未调参/R-DLADCN，仅供参考；
P：0.9933
R：0.8444
F1：0.9128
mang：0.0228
mIOU：0.8135

建议：
1. 用原版CenterNet训练一下不旋转的，确定你的数据集可以收敛，并对收敛数据进行评估；
2. 修改backbone网络结构，调参；（不太建议，dla_dcn已经足够强大了）；
3. 更换新的数据源。

**Comment by ZeroE04** [comment]
更新一下predict.py试试，12/14日进行了修改
