### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by nhathoang0110** [ZeroE04/R-CenterNet#32]
The angle of my dataset is 0-180 or -90 to 90 ? thanks you

**Comment by ZeroE04** [comment]
My own dataset is 0-180, but in theory, both are OK.

**Comment by nhathoang0110** [comment]
I using my dataset but it don't work well. Can you elaborate on what to fix in the repo when using the new dataset?

**Comment by ZeroE04** [comment]
I just use labelGenerator to label my data, then, train it.
“don't work well” means that the effect is not good or there is no work at all？

**Comment by nhathoang0110** [comment]
There is no work at all. In this repo, Are there any other fixes besides fixing hm vs numofclasses?

**Comment by nhathoang0110** [comment]
I have tested my dataset with the drawing function, which is as standard as your dataset. I think I have missing changes in the code, besides num_classes and hm, is there anything else I have to change to trainning?

**Comment by nhathoang0110** [comment]
I fixed num_class, self.class_name, self._valid_ids in dataset.py, hm in dlanet.py.

**Comment by nhathoang0110** [comment]
@ZeroE04  I think in the training file or in the prediction file, you have fixed many appropriate parameters for your dataset. can you check again Thank you very much

**Comment by ZeroE04** [comment]
Sorry, if I don't see your complete code, it's hard to find out why, just like other people, we can all run successfully.
