### ISSUE TITLE
有人成功用torch script生成了pt模型吗

### ISSUE THREAD

**Issue by leilaShen** [ZeroE04/R-CenterNet#33]
我用的piou+centerOBB， trace成功了模型 但是模型不对，看网上有人说应该用script  但script只支持python的子集 需要修改forward的代码，修改到DLAUp的getAttr(self, "proj_" + str(startp - i)) 这种代码就修改不下去了，因为script不支持动态函数，请教大神们有成功把centernet这一类的模型给成功script的吗 （不是用trace的哈），可否参考一下script修改的forward源码 谢谢！

**Comment by Wang-Qinyu** [comment]
My loss no longer converges after it drops to about 1.5, which is very strange.

**Comment by leilaShen** [comment]
已经解决了  我以为是trace有问题 其实trace生成的模型没有问题  关键在前处理  需要对tensor进行一次contigous操作
