### ISSUE TITLE
效果如何

### ISSUE THREAD

**Issue by wushilian** [ZeroE04/R-CenterNet#4]
在dota数据上效果怎么样？

**Comment by ZeroE04** [comment]
> 在dota数据上效果怎么样？

dota数据我没测试，知乎我文章评论里面 sdy344 测试过，你们可以交流一下

**Comment by ming71** [comment]
> 在dota数据上效果怎么样？

请问在dota上能实现多少的mAP？谢谢。

**Comment by hehu56** [comment]
在自己的训练数据集上测试，为什么效果不是很好呢，达不到过拟合的效果。请问有什么办法吗 @ZeroE04
