### ISSUE TITLE
如何用Libtorch调用生成的pt文件

### ISSUE THREAD

**Issue by CF-chen-feng-CF** [ZeroE04/R-CenterNet#40]
我将骨干网络改成了resnet18，并成功生成了pt格式（如以下代码），但是在Libtorch上调用时出错了，我怀疑是不是模型的输出接口用的是列表的形式，在Libtorch中无法识别，请问有什么样的解决办法吗？

//python生成pt格式模型：
model = ResNet(18)
model.load_state_dict(torch.load("ResNet18_best.pth"))
model.to("cpu")
traced_script_module = torch.jit.trace(model,torch.ones(1,3,512,512), strict=False)
traced_script_module.save("1.pt")

//Libtorch调用代码
torch::jit::script::Module model;
model = torch::jit::load("./1.pt");

//Libtorch调用时显示的错误：
Assertion failed: idx < size(), file C:\b\windows\pytorch\c10/util/SmallVector.h, line 201

**Comment by ZeroE04** [comment]
可以使用onnxruntime，参考[https://github.com/ZeroE04/CenterNet_onnxruntime](url)
