### ISSUE TITLE
About variance and standard.

### ISSUE THREAD

**Issue by Wang-Qinyu** [ZeroE04/R-CenterNet#43]
Why this project does not need to provide the variance and standard deviation of the datasets like orign [CenterNet](https://github.com/xingyizhou/CenterNet)

**Comment by steven22tom** [comment]
As the author said, this project is extremely compact code of CenterNet.
The mean and standard deviation of the datasets has already been calculated and provided.
[In dataset.py Line 20](https://github.com/ZeroE04/R-CenterNet/blob/master/dataset.py#L20)

**Comment by ZeroE04** [comment]
> As the author said, this project is extremely compact code of CenterNet.
> The mean and standard deviation of the datasets has already been calculated and provided.
> [In dataset.py Line 20](https://github.com/ZeroE04/R-CenterNet/blob/master/dataset.py#L20)

yep
