### ISSUE TITLE
关于类别计算问题

### ISSUE THREAD

**Issue by zhaowendao30** [ZeroE04/R-CenterNet#45]
![图片](https://user-images.githubusercontent.com/49309820/123225738-95389c00-d505-11eb-8293-c5f462715183.png)
大佬你好，我想问一下关于predict里面的tmp_c是指这次预测的类别么？为啥要这么计算呢？不应该直接是i么，属于哪个类别热力图就算哪个类别

**Comment by ZeroE04** [comment]
自己看懂代码。
