### ISSUE TITLE
angle_loss无法收敛的原因，其他loss均收敛

### ISSUE THREAD

**Issue by 19706** [ZeroE04/R-CenterNet#49]
使用不同backbone的情况下，在多种实验下表明，只有dla34_dcn的backbone的angle_loss可以收敛，其他backbone包括resdcn_50,101，以及dlav0_34，angle_loss均无法有效收敛，其他head的loss表现均不错，这个问题可能是什么？角度的量纲？感受野？还是？

**Comment by ZeroE04** [comment]
自己查查代码，你说的这几个backbone我都试验过，都可以收敛。
