### ISSUE TITLE
去掉ang后evalution代码报错

### ISSUE THREAD

**Issue by ztb520** [ZeroE04/R-CenterNet#51]
作者你好！我尝试使用这个工程去做行人检测，由于数据集问题，我去掉了旋转角，修改后可以正常训练模型，但是在模型评估阶段，我同样去掉了ang相关的内容，使用普通的iou。但是all_pre_num和num的输出都是0。我尝试去寻找哪里出了问题，在evalution.py文件的get_pre_ret函数中打印res = np.delete(res, 0, 0)之后得到的res=[],这是为什么呢？
我将修改之后的evalution和predict代码放在了csdn里：
[https://blog.csdn.net/weixin_43786395/article/details/121322506?spm=1001.2014.3001.5501](url)

如果您能有时间有时间浏览，将会非常感谢！！！

**Comment by ZeroE04** [comment]
为什么不用原版的CenterNet？
