### ISSUE TITLE
数据集中旋转角度都是0，旋转角度loss权重为0，会对神经网络和输出有什么影响？

### ISSUE THREAD

**Issue by ztb520** [ZeroE04/R-CenterNet#52]
作者你好！如果将输入的数据集中的旋转角全部设置为0，loss中计算旋转角的loss，会对卷积网络和最后的模型有什么影响吗？

**Comment by ZeroE04** [comment]
没啥影响；不过那为什么不直接用原版CenterNet？

**Comment by ztb520** [comment]
因为这个代码比较简单易懂，所以就用了这个。
还有就是想请问一下，这个工程中的训练集和验证集中的数据为什么是一样的呢？ 我扩展了一下数据集(仍然是检测飞机)，一个800张图片，600张做训练集，200张做验证集。训练时它们的loss一直不下降，都在8左右，这是什么原因呢？
